# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' meanC()
#' @description
#' Computes mean of numeric vector
#'
#' @param x Vector
#'
#' @details
#' \code{meanC} computes the mean of a vector using Rcpp
#'
#' @return
#' Returns a mean associated with a numeric vector. 
#'
#' @export
meanC <- function(x) {
    .Call('marcinlib_meanC', PACKAGE = 'marcinlib', x)
}

